# Use root/example as user/password credentials
version: '3.1'

services:

  ninjasmysql:
    container_name: ninjasmysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ninjas
      MYSQL_USER: hokage
      MYSQL_PASSWORD: hokage123
      MYSQL_ROOT_PASSWORD: konoha123
    ports:
      - 3306:3306
    volumes:
      - ./docker/db:/var/lib/mysql